In [1]:
import numpy as np
from hansolo import *

M = 2502
Nb=100
phi = 10
Kcc = 6
K_output=2
lamb_cc = np.array([0.005 for m in range(M)])
answers = np.zeros((Nb,M))
learning ='blocs'

obj = [
    [1, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1],
    [0, 1, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0, 1],
]



Wcc=np.zeros((K_output,Kcc,M,Nb))

for nb in range(Nb):
    if learning == 'blocs':
        L=list_obj_random(obj,M)
    else:
        L=list_objects_random(obj,M)

    mask = np.array([in_A(L[m])for m in range(M)])
    #print(mask)

    # Create an array of ones and -1s based on the mask
    tau_A = np.where(mask, 1, -1)
    tau_B=-tau_A
    true_cat = np.where(mask, 0, 1) #0 if A, 1 if B

    for m in range(M):
        obj_cur=L[m] #vector of a_im
        O_A=np.sum(np.array(obj_cur)*Wcc[0,:,m,nb])
        O_B=np.sum(np.array(obj_cur)*Wcc[1,:,m,nb])
        categorization=simu_dist([np.exp(phi*O_A)/np.exp(phi*O_A+phi*O_B),np.exp(phi*O_B)/(np.exp(phi*O_A+phi*O_B)) ]) # 0 if A, 1 if B
        if categorization == true_cat[m]:
            answers[nb,m]=1
    
        if m<M-1:
            Wcc[0,:,m+1,nb]=Wcc[0,:,m,nb]+lamb_cc[m]*obj_cur*(tau_A[m]-O_A)
            Wcc[1,:,m+1,nb]=Wcc[1,:,m,nb]+lamb_cc[m]*obj_cur*(tau_B[m]-O_B)
    print(nb)

np.save(f"{learning}_CC", answers)
np.save(f"{learning}_W_CC", Wcc)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [12]:
import numpy as np
from hansolo import *
obj = [
    [1, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1],
    [0, 1, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0, 1],
]
M=18
L=list_objects_random(obj,M)

# Assuming you have a NumPy array L
# You can create a boolean mask for elements in L that satisfy the condition
mask = np.array([in_A(L[m])for m in range(M)])
print(mask)

# Create an array of ones and -1s based on the mask
tau_A = np.where(mask, 1, -1)

print(L)
print(tau_A)

true_cat = np.where(mask, 0, 1) #0 if A, 1 if B
print(true_cat)


[ True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True False  True]
[[0 1 0 1 0 0]
 [0 0 1 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 1 0 0]
 [0 1 0 1 0 0]
 [0 0 1 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 1 0]
 [0 1 0 0 1 0]
 [0 1 0 0 0 1]
 [1 0 0 0 1 0]
 [1 0 0 0 1 0]
 [0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [0 0 1 0 0 1]
 [0 0 1 0 1 0]
 [1 0 0 1 0 0]
 [0 1 0 0 1 0]]
[ 1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
